### ISSUE TITLE
SOASTA Repo Token

### ISSUE THREAD

**Issue by jhonparedes** [SOASTA/repository.js#39]
This is not really an issue as opposed to a general inquiry. 

I'm trying to avoid having to repeatedly fetch the soasta repository token. I'm using this library to create some repo objects, however I'm also using [Annotations API](https://docs.soasta.com/annotations-api/) to retrieve information. The Annotations API requires a token which I'm getting from the [Repo Token API](http://docs.soasta.com/repository-api/#tokens). 

I'm wondering since I'm already getting a token when I do a `this.connect` call, would it make sense to return that token on the callback and use that to set a cookie which I can reuse for the Annotations API instead of having to do a second call to the Repo Token API. 

I know that the comment suggests that `the caller shouldn't need it for anything.` but would this be a plausible scenario?

```js
// path: /soasta-repository/lib/model/Repository.js
this.connect = function(tenantName, userName, password, callback) {
            var wrapper = function(error, token) {
                log.debug("Got token: " + token + " or error: " + error);
                self.token = token;

                // We don't pass the token on, since the caller shouldn't need it for anything.
                if (callback) {
                    callback(error);
                }
            };

            // Call the Tokens API with our wrapper.
            tokens.connect(tenantName, userName, password, wrapper);
};
```

**Comment by andreas-marschke** [comment]
Hey! The second callback param for connect is actually the token. Check SOASTA/repository.js/blob/master/lib/model/Tokens.js

**Comment by jhonparedes** [comment]
Got it! Thank you. I was able to get token from the repo.token and self context.
